bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

how_to/urls.py
from . import views
from django.urls import path
from .views import HowToDetail

urlpatterns = [
    path("", views.HowToList.as_view(), name="skincare_articles"),
    path('<slug:slug>/', views.HowToDetail.as_view(), name='howto_detail'),
]

pure_glow/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('how_to/', include('how_to.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

how_to/models.py
from django.db import models
from django.contrib.auth.models import User


class HowTo(models.Model):
    article_title = models.CharField(max_length=210, unique=True)
    slug = models.SlugField(max_length=210, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name="article_posts")
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='article_likes',
                                   blank=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.article_title

    def number_of_likes(self):
        return self.likes.count()


class ArticleComment(models.Model):
    post = models.ForeignKey(HowTo, on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    comment_body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return f"Comment {self.comment_body} by {self.name}"

how_to/forms.py
from .models import ArticleComment, HowTo
from django import forms


class ArticleCommentForm(forms.ModelForm):
    class Meta:
        model = ArticleComment
        fields = ('comment_body',)


class ArticleForm(forms.ModelForm):
    class Meta:
        model = HowTo
        fields = ('article_title', 'content', 'image')

how_to/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views import generic, View
from .models import HowTo, ArticleComment
from .forms import ArticleCommentForm, ArticleForm
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin


class HowToList(generic.ListView):
    model = HowTo
    template_name = "articles.html"


class HowToDetail(View):

    def get(self, request, slug, *args, **kwargs):
        queryset = HowTo.objects
        post = get_object_or_404(queryset, slug=slug)
        comments = post.comments.filter(approved=True).order_by("-created_on")

        return render(
            request,
            "articles_detail.html",
            {
                "post": post,
                "comments": comments,
                "comment_form": ArticleCommentForm()
            },
        )

    def post(self, request, slug, *args, **kwargs):

        queryset = HowTo.objects
        post = get_object_or_404(queryset, slug=slug)
        comments = post.comments.filter(approved=True).order_by("-created_on")

        comment_form = ArticleCommentForm(data=request.POST)
        if comment_form.is_valid():
            comment_form.instance.email = request.user.email
            comment_form.instance.name = request.user.username
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.save()
        else:
            comment_form = ArticleCommentForm()

        return render(
            request,
            "articles_detail.html",
            {
                "post": post,
                "comments": comments,
                "commented": True,
                "comment_form": ArticleCommentForm()
            },
        )

how_to/templates/articles.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container-fluid">
        <div class="row">
            <div class="col text-center mt-3">
                <h2 class="logo-font">Skincare Articles</h2>
                <br>
            </div>
        </div>
        <div class="row">
            <div class="product-container col-10 offset-1">
                <div class="row">
                    {% for howto in howto_list %}
                        <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3">
                            <div class="card h-100 border-0">
                                {% if howto.image %}
                                <a href="{% url 'howto_detail' howto.slug %}">
                                    <img class="card-img-top img-fluid howto-rollover" src="{{ howto.image.url }}" alt="{{ howto.name }}">
                                </a>
                                {% else %}
                                <a href="{% url 'howto_detail' howto.slug %}">
                                    <img class="card-img-top img-fluid howto-rollover" src="{{ MEDIA_URL }}noimage.png" alt="{{ howto.name }}">
                                </a>
                                {% endif %}
                                <div class="card-body pb-0">
                                    <h2 class="mb-0">{{ howto.article_title }}</h2>
                                </div>
                                <div class="card-footer bg-white pt-0 border-0 text-left">
                                    <div class="row">
                                        <div class="col">
                                            <p class="author lead mb-0 text-left font-weight-bold">by {{ howto.author }}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% if forloop.counter|divisibleby:1 %}
                            <div class="col-12 d-sm-none mb-5">
                            </div>
                        {% endif %}                        
                        {% if forloop.counter|divisibleby:2 %}
                            <div class="col-12 d-none d-sm-block d-md-block d-lg-none mb-5">
                            </div>
                        {% endif %}
                        {% if forloop.counter|divisibleby:3 %}
                            <div class="col-12 d-none d-lg-block d-xl-none mb-5">
                            </div>
                        {% endif %}
                        {% if forloop.counter|divisibleby:4 %}
                            <div class="col-12 d-none d-xl-block mb-5">
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <!-- Back to Top Button -->
    <div class="btt-button shadow-sm rounded-0 border border-black" id="backtotop">
        <a class="btt-link d-flex h-100">
            <i class="fas fa-arrow-up text-black mx-auto my-auto"></i>
        </a>	
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script>
		$('.btt-link').click(function(e) {
			window.scrollTo(0,0)
		})
	</script>
    
    <script>
        $('#sort-selector').change(function() {
            var selector = $(this);
            var currentUrl = new URL(window.location);

            var selectedVal = selector.val();
            if(selectedVal != "reset"){
                var sort = selectedVal.split("_")[0];
                var direction = selectedVal.split("_")[1];

                currentUrl.searchParams.set("sort", sort);
                currentUrl.searchParams.set("direction", direction);

                window.location.replace(currentUrl);
            } else {
                currentUrl.searchParams.delete("sort");
                currentUrl.searchParams.delete("direction");

                window.location.replace(currentUrl);
            }
        })
    </script>
{% endblock %}

how_to/templates/articles_detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-md-4 col-lg-3 offset-lg-1">
                <!-- How to Article image -->
                <div class="image-container my-5">
                    {% if post.image %}
                    <a>
                        <img class="card-img-top img-fluid" src="{{ post.image.url }}" alt="{{ howto.name }}">
                    </a>
                    {% else %}
                    <a>
                        <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="{{ howto.name }}">
                    </a>
                    {% endif %}
                </div>
            </div>
            <!-- How to Article details section -->
            <div class="col-12 col-md-8 col-lg-6">
                <div class="product-details-container mb-5 mt-md-5">
                    <h2 class="mb-0">{{ post.article_title }}</h2>
                    <p class="author lead mb-0 text-left font-weight-bold">by {{ post.author }}</p>
                    <p class="mt-3">{{ post.content | safe }}</p>
                </div>
                <div class="row">
                    <div class="col">
                        <hr class="line-break">
                    </div>
                </div>
                <!-- Comments section -->
                <div class="row">
                    <div class="col-md-8 card mb-4  mt-3">
                        <h2>Comments:</h2>
                        <div class="card-body">
                            <!-- Loop to iterate through each comment -->
                            {% for comment in comments %}
                            <div class="comments">
                                <p class="font-weight-bold">
                                    <!-- The commenter's name -->
                                    {{ comment.name }}
                                    <span class="text-muted font-weight-normal">
                                        <!-- Comment's created date -->
                                        {{ comment.created_on }}
                                    </span> wrote:
                                </p>
                                <!-- The body of the comment -->
                                {{ comment.comment_body | linebreaks }}
                            </div>
                            <!-- For loop ends here -->
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-md-4 card mb-4  mt-3 ">
                        <div class="card-body">
                            <!-- Comment awaiting approval message -->
                            {% if commented %}
                            <div class="alert alert-success" role="alert">
                                Thank you! Your comment is awaiting approval.
                            </div>
                            {% else %}
                            {% if user.is_authenticated %}
            
                            <h3>Leave a comment:</h3>
                            <p>Posting as: {{ user.username }}</p>
                            <form method="post" class="commentform" autocomplete="off">
                                {{ comment_form | crispy }}
                                {% csrf_token %}
                                <button type="submit" class="btn btn-signup btn-lg btn-brown">Submit</button>
                            </form>
                            {% endif %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}